
# Needed packages to perform the analysis
```{r}
load <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
} 

packages <- c("knitr","dplyr",
              "ggplot2","bvpSolve","deSolve","class","pracma","tidyr")
load(packages)
```

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
### get the arguments
args = commandArgs(TRUE)
pos <- as.numeric(args[1])+as.numeric(args[2])
R0.cases <- args[3]
if(is.na(pos)){
  pos <- 1
  R0.cases <- 6
}
```
        
   
```{r}
twoComparmentSIRmu <- function(x, y, parms) {
  
  with(as.list(c(y, parms)),{
    s1 <- y[1]
    s2 <- y[2]
    i1 <- y[3]
    i2 <- y[4]
    mu1 <- y[5]
    mu2 <- y[6]
    nu1 <- y[7]
    nu2 <- y[8]
    
    
    rho11 <- (r11*a11)/(a11+r11*s1*i1*(mu1-nu1))
    rho12 <- (r12*a12)/(a12+r12*s1*i2*(mu1-nu1))
    rho21 <- (r21*a21)/(a21+r21*s2*i1*(mu2-nu2))
    rho22 <- (r22*a22)/(a22+r22*s2*i2*(mu2-nu2))

    ds1 <- -s1*rho11*i1-s1*rho12*i2
    ds2 <- -s2*rho21*i1-s2*rho22*i2
    di1 <- s1*rho11*i1+s1*rho12*i2-i1
    di2 <- s2*rho21*i1+s2*rho22*i2-i2
    
    dmu1 <- (rho11*i1+rho12*i2)*(mu1-nu1)
    dmu2 <- (rho21*i1+rho22*i2)*(mu2-nu2)
    dnu1 <- s1*rho11*(mu1-nu1)+s2*rho21*(mu2-nu2)+nu1
    dnu2 <- s1*rho12*(mu1-nu1)+s2*rho22*(mu2-nu2)+nu2

    g <- function(x){
      y <- -log(x)+x-1
      return(y)
    }
    dCost <- a11*rho11*g(rho11/r11)+a12*rho12*g(rho12/r12)+a21*rho21*g(rho21/r21)+
      a22*rho22*g(rho22/r22)
    
    if(is.nan(dCost)){
      dCost <- 0
    }
    
    return(list(c(ds1,ds2,di1,di2,dmu1,dmu2,dnu1,dnu2,dCost)))
  })
}
```



```{r}
exper.design <- read.csv("INTERMEDIATE/exper.design.mu.2group.csv")

neighbors <- exper.design %>%
  pivot_longer(cols = starts_with("neighbor_"),
               names_to = "name",
               values_to = "neighbor_num") 
neighbors$neighbor_solved <- FALSE
```

```{r}
    solved.count <- 0
```

```{r}
for(pos in 1:dim(exper.design)[1]){
print(Sys.time())
        c.tried <- c()
        
  case.id <- exper.design$case.id.mu[pos]
  print(case.id)
   tFinal <- exper.design$tFinal[pos]
   # c needs to become s (select s final from exper.design)
   sFinal <- exper.design$sFinal[pos]
   R_0 <- exper.design$R0[pos]
   i0 <- exper.design$i0[pos]
   delta <- exper.design$delta[pos]
    t <- seq(0,tFinal,.2)
    t.temp <- t
    
    #s <- y[1] 
    #i <- y[2] 
    #mu_s <- y[3]
    #mu_i <- y[4]
    s.init <- (1-i0)/2
    i.init <- i0/2
    yini = c(s.init,s.init,i.init,i.init,NA,NA,NA,NA)
    yend = c(sFinal/2,(sFinal-delta)/2,NA,NA,NA,NA,0,0)
    solved <- FALSE


  unique.costs <- c()
 
    solved <- FALSE


    res <- try(guess <- bvpshoot(yini = yini,yend=yend,x=t,parms = list(r11=R_0,r12=R_0,r21=R_0,r22=R_0,a11=.25,a12=.25,a21=.25,a22=.25),
                         func = twoComparmentSIRmu,maxit=5),
               silent=TRUE)
  
    if(!inherits(res, "try-error")){
      print("validating")

      xguess <- guess[,1]
      yguess <- t(guess[,2:9])
    res <- try(bvptwp(yini = yini,yend=yend,x=t,parms = list(r11=R_0,r12=R_0,r21=R_0,r22=R_0,c=1,a11=1,a12=1,a21=1,a22=1,c=1),func = twoComparmentSIRmu,
              xguess = xguess,yguess = yguess,nmax=length(t)*20))
    }
      solved <- !inherits(res, "try-error")
      print(solved)
      if(solved==TRUE){
        print(solved.count)
        solved.count <- solved.count +1
        sol <- as.data.frame(res)
        sol <- sol[,1:9]
         sol <- sol[!duplicated(sol),]
        sol.cost <- round(tail(sol[,6],n=1),6)
        names(sol) <- c("x",as.character(1:5))
        stop()
        sol <- as.data.frame(sol) %>% 
          rename(tau=x,s='1',i='2',mu_s='3',mu_i='4',Cost='5') %>% 
          mutate(R_tau = R_0/(1+R_0*s*i*(mu_s-mu_i)),
                 Rt= R_tau*s,
                 tFinal=tFinal,
                 case.id = case.id)
            sol <- subset(sol,tau %in% t)
        sol$case.id <- case.id
        sol$R0 <- R_0
        sol$tFinal <- tFinal
        sol$sFinal <- sFinal
        sol$i0 <- i0
        sol$solved <- solved
        exper.design[pos,"solved"] <- TRUE
        neighbors[which(neighbors$neighbor_num==case.id),"neighbor_solved"] <- TRUE
        neighbors[which(neighbors$case.id.mu==case.id),"solved"] <- TRUE
        
        if(solved.count == 1){
          sol.explore2 <- sol
        } else {
          sol.explore2  <- bind_rows(sol.explore2,sol)
        }
      }
 
    
          

    print(solved)
print(Sys.time())

}


write.csv(sol.explore2,"INTERMEDIATE/mu.solutions0.2groups.csv",row.names=FALSE)
write.csv(exper.design,"INTERMEDIATE/exper.design.mu0.2groups.csv",row.names=FALSE)
write.csv(neighbors,"INTERMEDIATE/mu.neighbors0.2groups.csv",row.names=FALSE)
iter.num <- 0
save(iter.num,file="iter.num.2groups.Rdata")
#source("BVP-dimless-mu-test.R")
```


