---
title: "Calculus of Variations Approach to Social Distancing"
output: powerpoint_presentation
---

```{r,echo=FALSE}
require(ggplot2)
require(viridis)
require(ggthemes)
require(rootSolve)
```
```{r,echo=FALSE}
d <- read.csv("INTERMEDIATE/sol.explore-step12.csv")
dm <- read.csv("INTERMEDIATE/sol.explore-myopic.csv")
e <- read.csv("INTERMEDIATE/exper.design-step11.csv")
```

```{r,echo=FALSE}
row.names(e) <- e$case.id
d$R0 <- e[d$case.id,"R0"]
d$tFinal <- e[d$case.id,"tFinal"]
d$i0 <- e[d$case.id,"i0"]
d$c <- e[d$case.id,"c"]
d$twp.success <- e[d$case.id,"twp.success"]

d$optimization <- "full"
dm$optimization <- "myopic"
dm$twp.success <- NA
dm$R0 <- e[dm$case.id,"R0"]
dm$tFinal <- e[dm$case.id,"tFinal"]
dm$i0 <- e[dm$case.id,"i0"]
dm$c <- e[dm$case.id,"c"]
d <- rbind(d,dm)

```

```{r,echo=FALSE}
d <- subset(d,c %in% c(0.025, 0.05, 0.1, 0.2, 0.4))
d$RD <- d$R_tau
```

```{r,echo=FALSE}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$tFinal == 8&d$optimization == "full",], aes(x = tau,y = Rrel,color = as.factor(c),group = c))+geom_line()+facet_grid(i0~R0)+scale_color_viridis(end = 0.75,discrete = TRUE)
g
```
```{r}
f1.5 <- function(x,R0){exp(-1.5*(1-x))-x}
f2.5 <- function(x,R0){exp(-2.5*(1-x))-x}
f5 <- function(x,R0){exp(-5*(1-x))-x}
```
```{r}

Sinf1.5 <- multiroot.1D(f=f1.5,start = .5,nspec= 1)[["root"]]
Sinf2.5 <- multiroot.1D(f=f2.5,start = .5,nspec= 1)[["root"]]
Sinf5 <- multiroot.1D(f=f5,start = .5,nspec= 1)[["root"]]

S1.5max <- 1/1.5
S2.5max <- 2.5
S5max <- 5
d$months <- d$tau/2
d$tFinal <- factor(d$tFinal,levels = c(8,16, 32, 64, 128),labels = c("4","8","16","32","64"))
```

```{r,echo=FALSE,dpi=600}
aux <- d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.4) & d$tFinal == 64 &d$optimization == "full",]

aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"

require(tidyr)
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"
x <- seq(0.01,1,.01)
y <- -log(x)+x-1
p <- as.data.frame(cbind(x,y))
g <- ggplot(p,aes(x=x,y=y))+geom_line()+theme_bw()+scale_x_continuous(breaks = c(0,.2,.4,.6,.8,1),labels = c(0, "0.2*R0","0.4*R0","0.6*R0","0.8*R0","R0"))+xlab("RD")+ylab("Social Distaning Cost Per Unit Time")+scale_y_continuous(breaks= c(0,1,2,3),labels = c(0, "c", "2*c","3*c"))
g
```

```{r,echo=FALSE,dpi=600}
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"

require(tidyr)
aux <- d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.4) & d$tFinal == 64 &d$optimization == "full",]
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"
aux.long <- gather(aux,key="key",value = "value",c("i","s","R_tau","Rt","RD"))

g <- ggplot(aux.long[aux.long$key %in% c("i","s"),], aes(x = tau,y = value,linetype=key))+geom_line()+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+scale_y_continuous(limits = c(0,1))+facet_grid(.~c)+ylab("")+geom_hline(yintercept=Sinf1.5,linetype="dashed",color="red")+geom_hline(yintercept=S1.5max,linetype="dashed",color="red")

g
```

```{r,echo=FALSE,dpi=600}

require(tidyr)
g <- ggplot(aux.long[aux.long$key %in% c("RD","Rt"),], aes(x = tau,y = value,linetype = key))+geom_line()+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+scale_y_continuous(limits = c(0,1.5))+facet_grid(.~c)+ylab("")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```



```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025) & d$optimization == "full",], aes(x = tau,y = Rrel,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")

g
```

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$i0 %in% c(0.0001,0.0051)&d$c%in% c(0.025)&d$R0 %in% c(1.5)&d$optimization=="full",], aes(x = tau,y = Rrel,linetype = as.factor(i0),color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")+scale_linetype(name = "i0")

g
```

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$i0 %in% c(0.0001,0.0051)&d$c%in% c(0.025)&d$R0 %in% c(1.5)&d$optimization=="myopic",], aes(x = tau,y = Rrel,linetype = as.factor(i0),color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")+scale_linetype(name = "i0")

g
```


# R_D/R_0, Social Distancing Over Time

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025)&d$optimization=="full",], aes(x = tau,y = Rrel,linetype = as.factor(i0),color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")

g
```


```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05)&d$optimization=="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4)],aesthetics = "color",name="c")
g
```

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1)&d$optimization=="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3)],aesthetics = "color",name="c")
g
```

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2)&d$optimization == "full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2)],aesthetics = "color",name="c")
g
```

# RD, R0 = 1.5

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```


```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="myopic",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```


```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 2.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization =="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```


```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 2.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&((d$c == 0.025 & d$tFinal == "64")|(d$c == 0.05 & d$tFinal == "32"))&d$optimization =="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("RD/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```


# RD, R0 = 5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = Rrel,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R/R0")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```

# Infected, R0 = 1.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025),], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.05))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")
g
```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025)&d$optimization=="full",], aes(x = tau,y = Rt,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R_effective")+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05)&d$optimization=="full",], aes(x = tau,y = Rt,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R_effective")+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4)],aesthetics = "color",name="c")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,0.1)&d$optimization=="full",], aes(x = tau,y = Rt,linetype = as.factor(i0),color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R_effective")+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4,3)],aesthetics = "color",name="c")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,0.1,.2)&d$optimization=="full",], aes(x = tau,y = Rt,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R_effective")+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4,3,2)],aesthetics = "color",name="c")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,0.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = Rt,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("R_effective")+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=1,linetype="dashed",color="red")

g
```
# Infected, R0 = 1.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05),], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.05))+scale_fill_manual(values=viridis(6)[c(5,4)],aesthetics = "color",name="c")
g
```

# Infected, R0 = 1.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1)&d$optimization=="full",], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.05))+scale_fill_manual(values=viridis(6)[c(5,4,3)],aesthetics = "color",name="c")
g
```
# Infected, R0 = 1.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2)&d$optimization=="full",], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.05))+scale_fill_manual(values=viridis(6)[c(5,4,3,2)],aesthetics = "color",name="c")
g
```

# Infected, R0 = 1.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.05))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```
# Infected, R0 = 2.5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 2.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4),], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.2))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```
# Infected, R0 = 5
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4),], aes(x = tau,y = i,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Infected")+scale_y_continuous(limits = c(0,.5))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")
g
```

# Susceptibles Different Time Horizons

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5)],aesthetics = "color",name="c")
g
```

# Susceptibles Different Time Horizons

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4)],aesthetics = "color",name="c")
g
```

# Susceptibles Different Time Horizons

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3)],aesthetics = "color",name="c")
g
```

# Susceptibles Different Time Horizons

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2)],aesthetics = "color",name="c")
g
```



```{r}

Sinf1.5 <- multiroot.1D(f=f1.5,start = .5,nspec= 1)[["root"]]
Sinf2.5 <- multiroot.1D(f=f2.5,start = .5,nspec= 1)[["root"]]
Sinf5 <- multiroot.1D(f=f5,start = .5,nspec= 1)[["root"]]

S1.5max <- 1/1.5
S2.5max <- 1/2.5
S5max <- 1/5
```
# Susceptibles, R0 = 1.5


```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=Sinf1.5,linetype="dashed",color="red")+geom_hline(yintercept=S1.5max,linetype="dashed",color="red")
g
```

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="myopic",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=Sinf1.5,linetype="dashed",color="red")+geom_hline(yintercept=S1.5max,linetype="dashed",color="red")
g
```

# Susceptibles, R0 = 2.5

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 2.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=Sinf2.5,linetype="dashed",color="red")+geom_hline(yintercept=S2.5max,linetype="dashed",color="red")
g
```

# Susceptibles, R0 = 2.5

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 2.5&d$i0==0.0001&((d$c == 0.025 & d$tFinal == "64")|(d$c == 0.05 & d$tFinal == "32"))&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=Sinf2.5,linetype="dashed",color="red")+geom_hline(yintercept=S2.5max,linetype="dashed",color="red")
g
```


# Susceptibles, R0 = 5

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
g <- ggplot(d[d$R0 == 5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = s,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme_bw()+scale_x_continuous(breaks = c(8,16,32,64,128),labels = c("4","8","16","32","64"))+xlab("Time (in Months)")+ylab("Proportion Susceptible")+scale_y_continuous(limits = c(0,1))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+geom_hline(yintercept=Sinf5,linetype="dashed",color="red")+geom_hline(yintercept=S5max,linetype="dashed",color="red")
g
```


