---
title: "Calculus of Variations Approach to Social Distancing"
output: powerpoint_presentation
---

```{r,echo=FALSE}
require(ggplot2)
require(viridis)
require(ggthemes)
require(rootSolve)
require(latex2exp)
library(dplyr)
library(reshape2)
library(stringr)
library(fields)
library(DescTools)
library(Bolstad2)
source("FUNCTIONS/CalculateCost.R")
```

```{r,echo=FALSE}
multR015 <- read.csv("INTERMEDIATE/multR015.csv")
d <- multR015
```

```{r,echo=FALSE}
theme_set(theme_bw())
```

```{r,echo=FALSE}
d$RD <- d$R_tau
```


```{r}
f1.5 <- function(x,R0){exp(-R0*(1-x))-x}
```
```{r}

Sinf1.5 <- multiroot.1D(f=f1.5,start = .5,nspec= 1)[["root"]]
Sinf2.5 <- multiroot.1D(f=f2.5,start = .5,nspec= 1)[["root"]]
Sinf5 <- multiroot.1D(f=f5,start = .5,nspec= 1)[["root"]]

S1.5max <- 1/1.5
S2.5max <- 2.5
S5max <- 5
d$months <- d$tau/2
d$tFinal <- factor(d$tFinal,levels = c(8,16, 32, 64, 128))
```

```{r,echo=FALSE,dpi=600}
aux <- d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.4) & d$tFinal == 64 &d$optimization == "full",]
```

```{r}
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"

require(tidyr)
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation (Herd Immunity)"
x <- seq(0.01,1,.01)
y <- -log(x)+x-1
p <- as.data.frame(cbind(x,y))
g <- ggplot(p,aes(x=x,y=y))+geom_line()+theme_bw()+scale_x_continuous(breaks = c(0,.2,.4,.6,.8,1),labels = c(0, "0.2","0.4","0.6","0.8","1"))+xlab("RD")+ylab("g(x)")+xlab("x")+scale_y_continuous(breaks= c(0,1,2,3),labels = c(0, "1", "2","3"))
g
```

```{r,echo=FALSE,dpi=600}
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation"

require(tidyr)
aux <- d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.4) & d$tFinal == 64 &d$optimization == "full",]
aux$c[aux$c == 0.025] <- "Suppression"
aux$c[aux$c == 0.4] <- "Mitigation"
aux.long <- gather(aux,key="key",value = "value",c("i","s","R_tau","Rt","RD"))

ann_text <- data.frame(tau=c(45,40),value = c(S1.5max,Sinf1.5),label=c("Max Suceptibles\n for Herd Immunity","Suceptibles Remaining in \n an Uncontrolled Epidemic"),key=c("s","s"),c=c("Mitigation","Mitigation"))

g <- ggplot(aux.long[aux.long$key %in% c("i","s"),], aes(x = tau,y = value,linetype=key))+geom_line()+xlab(TeX(r'($\tau$)'))+scale_y_continuous(limits = c(0,1))+facet_grid(.~c)+ylab("Proportion of Population")+geom_hline(yintercept=Sinf1.5,linetype="dashed",color="red")+geom_hline(yintercept=S1.5max,linetype="dashed",color="red")+scale_linetype(name="",labels=list(TeX(r'($i$)'),TeX(r'($s$)')))+geom_label(data=ann_text,aes(label=label),size=2.2,label.size = .1,label.padding=unit(.1,"lines"),label.r = unit(.1,"lines"))+theme(legend.position = "bottom")

#+annotate("label",x=40,y=Sinf1.5,label="Suceptibles Remaining in \n an Uncontrolled Epidemic")+annotate("label",x=50,y=S1.5max,c="Mitigation",label="Max Suceptibles\n for Herd Immunity")


g
```

```{r,echo=FALSE}
png(filename = "FIGS/MitSup.png",height = 3,width=4,units = "in",res = 800)
g
dev.off()

```

```{r,echo=FALSE,dpi=600}

require(tidyr)
g <- ggplot(aux.long[aux.long$key %in% c("RD","Rt"),], aes(x = tau,y = value,linetype = key))+geom_line()+theme_bw()+xlab(TeX(r'($\tau$)'))+scale_y_continuous(limits = c(0,1.5))+facet_grid(.~c)+ylab("")+geom_hline(yintercept=1,linetype="dashed",color="red")+scale_linetype_discrete(name="",breaks=c("RD","Rt"),labels=list(TeX(r'($R_D$)'),TeX(r'($R_{\tau}$)')))+theme(legend.position = "bottom")+ylab("Reproduction Number")

g
```
```{r,echo=FALSE}
png(filename = "FIGS/MitSup_policy.png",height = 3,width=4,units = "in",res = 800)
g
dev.off()

```











# RD, R0 = 1.5

```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
theme_set(theme_bw())
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="full",], aes(x = tau,y = RD,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme(legend.position = "bottom")+xlab(TeX(r'($\tau$)'))+ylab(TeX(r'($R_D$)'))+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+scale_x_continuous(breaks = c(8,16,32,64,128))
g
```
```{r,echo=FALSE}
png(filename = "FIGS/ChangeTFinal.png",height = 5,width=6,units = "in",res = 800)
g
dev.off()

```
```{r,echo=FALSE,dpi=600}
d$Rrel <- d$R_tau/d$R0
theme_set(theme_bw())
g <- ggplot(d[d$R0 == 1.5&d$i0==0.0001&d$c%in% c(0.025,0.05,.1,.2,.4)&d$optimization=="myopic",], aes(x = tau,y = RD,group = c,color=as.factor(c)))+geom_line()+facet_grid(.~tFinal,scales="free_x",space="free")+theme(legend.position = "bottom")+xlab(TeX(r'($\tau$)'))+ylab(TeX(r'($R_D$)'))+scale_y_continuous(limits = c(0,1.5))+scale_fill_manual(values=viridis(6)[c(5,4,3,2,1)],aesthetics = "color",name="c")+scale_x_continuous(breaks = c(8,16,32,64,128))
g
```
```{r,echo=FALSE}
png(filename = "FIGS/ChangeTFinal_myopic.png",height = 5,width=6,units = "in",res = 600)
g
dev.off()

```







```{r}

Sinf1.5 <- multiroot.1D(f=f1.5,start = .5,nspec= 1)[["root"]]
Sinf2.5 <- multiroot.1D(f=f2.5,start = .5,nspec= 1)[["root"]]
Sinf5 <- multiroot.1D(f=f5,start = .5,nspec= 1)[["root"]]

S1.5max <- 1/1.5
S2.5max <- 1/2.5
S5max <- 1/5
```





```{r}

fR0 <- function(x,R0){exp(-R0*(1-x))-x}


Sinf1.5 <- multiroot.1D(f=fR0,R0=1.5,start = .5,nspec= 1)[["root"]]
Sinf3 <- multiroot.1D(f=fR0,R0=3,start = .5,nspec= 1)[["root"]]
Sinf4.5 <- multiroot.1D(f=fR0,R0=4.5,start = .5,nspec= 1)[["root"]]
Sinf6 <- multiroot.1D(f=fR0,R0=6,start = .5,nspec= 1)[["root"]]


S1.5max <- 1/1.5
S3max <- 1/3
S4.5max <- 1/4.5
S6max <- 1/6

epi.size <- cbind(R0 = c(1.5,3,4.5,6),EpiInf = c(1-Sinf1.5,1-Sinf3,1-Sinf4.5,1-Sinf6),EpiMin = c(1-S1.5max,1-S3max,1-S4.5max,1-S6max))

all_cases = read.csv("INTERMEDIATE/sol.explore.all.csv")
all_cases2 <- read.csv("INTERMEDIATE/parallel.output2.csv")
all_cases3 <- read.csv("INTERMEDIATE/parallel.output3.csv")
all_casesR03 <- read.csv("INTERMEDIATE/output-R03.csv")
all_casesR045 <- read.csv("INTERMEDIATE/output-R045.csv")

all_cases4 <- rbind(all_cases,all_cases2,all_cases3)
all_cases4 <-  subset(all_cases4,solved==TRUE&R0!=3&R0!=4.5)
all_cases4 <- rbind(all_cases4,all_casesR03[,1:dim(all_cases4)[2]],all_casesR045[,1:dim(all_cases4)[2]])


myopic_data = read.csv("INTERMEDIATE/sol.explore-myopic20210730.csv") %>%
  dplyr::select(tau, s, i, R_tau, Rt, case.id)

myopic_exp_design = read.csv("INTERMEDIATE/exper.design-round13.csv") %>%
  dplyr::select(case.id, c, R0, i0, tFinal)

myopic_data <- left_join(myopic_data,myopic_exp_design)
```

```{r}
myopic_final_data = myopic_data %>%
  dplyr::filter(tFinal == tau&case.id>417&R0==1.5) %>%
  mutate(EpiSize = 1-s) 
```

```{r}

g <- myopic_final_data %>%
  ggplot(data = ., mapping = aes(x = tFinal, y = c, fill = EpiSize)) +
  geom_tile() + scale_fill_viridis_c(name="Final Epidemic Size")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")
g
```
```{r,echo=FALSE}
png(filename = "FIGS/myopic_tile_plot.png",height = 5,width=6,units = "in",res = 600)
g
dev.off()

```

```{r}
g2 <-  all_cases4 %>%
  dplyr::filter(tFinal == tau, case.id > 417,i0==0.0001,R0==1.5) %>%
  mutate(EpiSize = 1-s) %>%
  ggplot(data = ., mapping = aes(x = tFinal, y = c, fill = EpiSize)) +
  geom_tile() +geom_blank(data=myopic_final_data)+ scale_fill_viridis_c(name="Final Epidemic Size")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")
g2
```

```{r,echo=FALSE}
png(filename = "FIGS/tile_plot.png",height = 5,width=6,units = "in",res = 800)
g2
dev.off()

```
#Total Cost
```{r}
myopic_data1.5 = myopic_data %>%
  dplyr::filter(case.id>417&R0==1.5&i0==0.0001) %>%
  mutate(EpiSize = 1-s) 
```

```{r}
myopic_cost <- CalculateCost(myopic_data1.5)
```

```{r}
g <-  ggplot(myopic_cost, mapping = aes(x = tFinal, y = c, fill = cost)) +
  geom_tile() + scale_fill_viridis_c(name="Cost")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")
g

```

```{r}
full_opt1.5 <- all_cases4 %>%
  dplyr::filter(case.id > 417,i0==0.0001,R0==1.5)
```

```{r}
opt_cost <- CalculateCost(full_opt1.5)
```

```{r}
opt_cost$cost3 <- opt_cost$cost2
opt_cost <- as.data.frame(opt_cost)
```



```{r}
tFinal.vec <- seq(8,80,by=4)
g <-  multR015 %>%
  filter(tau == tFinal & is.min == TRUE & tFinal %in% tFinal.vec) %>%
  ggplot(mapping= aes(x = tFinal, y = c,fill=Cost)) +
  geom_tile() + scale_fill_viridis_c(name="Cost")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")+facet_wrap(.~ as.factor(i0))
g

```
```{r}
tFinal.vec <- seq(8,80,by=4)
g <-  multR015 %>%
  filter(tau == tFinal & is.min == FALSE & tFinal %in% tFinal.vec) %>%
  ggplot(mapping= aes(x = tFinal, y = c,fill=Cost)) +
  geom_tile() + scale_fill_viridis_c(name="Cost")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")+facet_wrap(.~ as.factor(i0))
g

```
```{r}
opt_cost$my_cost <- myopic_cost[row.names(opt_cost),"cost"]
```

```{r}
opt_cost$ratio <- opt_cost$my_cost/opt_cost$cost
```

```{r}
g <-  ggplot(opt_cost, aes(x = tFinal, y = c,fill=ratio)) +
  geom_tile() + scale_fill_viridis_c(name="Cost Ratio")+xlab(TeX(r'($T_{final}$)'))+theme(legend.position = "bottom")
g
```

```{r,echo=FALSE}
png(filename = "FIGS/RelCostMyopic.png",height = 3,width=4,units = "in",res = 800)
g
dev.off()

```



